[project]
name = "disgaea-pc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydirectinput>=1.0.4",
    "pynput>=1.7.7",
    "typer>=0.15.1",
]

[dependency-groups]
dev = [
    "ruff>=0.8.4",
]
